<?php

namespace ReservasBundle\Repository;

/**
 * PrecioTipoHabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioTipoHabRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPreciosTiposHabitacion() {

        $em     = $this->getEntityManager();

        $result = $em->createQueryBuilder()
            ->select('prec.id')
            ->addSelect('prec.tipoHabitacion')
            ->addSelect('prec.precioxdia')
            ->from('ReservasBundle:PrecioTipoHab','prec')
            ->getQuery()
            ->getArrayResult()
        ;

        return $result;
    }
}
