<?php

namespace ReservasBundle\Repository;
use ReservasBundle\Entity\Reservas;

/**
 * ReservasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservasRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDisponibilidad($fechallegada, $fechasalida) {

        $em     = $this->getEntityManager();

        $result = $em->createQueryBuilder()
            ->select('res.id')
            ->from('ReservasBundle:Reservas','res')
            ->where('res.llegada < :fechasalida')
            ->andWhere('res.salida >= :fechallegada')
            ->setParameter('fechallegada', $fechallegada)
            ->setParameter('fechasalida', $fechasalida)
            ->getQuery()
            ->getArrayResult()
        ;

        return $result;
    }

    public function createReserva(Reservas $reserva, $llegada, $salida, $tipohab, $tipopens,
                                  $precio, $nombre, $apellidos, $email,
                                  $telefono, $numadultos, $numninos, $numbebes, $voucher) {
        $reserva->setLlegada(new \DateTime($llegada));
        $reserva->setSalida(new \DateTime($salida));
        $reserva->setTipoHabitacion(strtoupper($tipohab));
        $reserva->setTipoPension(strtoupper($tipopens));
        $reserva->setPrecio($precio);
        $reserva->setNombre(strtoupper($nombre));
        $reserva->setApellidos(strtoupper($apellidos));
        $reserva->setEmail(strtolower($email));
        $reserva->setTelefono($telefono);
        $reserva->setNumAdultos((int)$numadultos);
        $reserva->setNumNinos((int)$numninos);
        $reserva->setNumBebes((int)$numbebes);
        $reserva->setVoucher(strtoupper($voucher));
        if (new \DateTime($llegada) < new \DateTime()) {
            if (new \DateTime($salida) < new \DateTime()) {
                $reserva->setEstado('CHECK-OUT');
            } else {
                $reserva->setEstado('CHECK-IN');
            }
        }

        return $reserva;
    }

    public function finMisReservas($nombre = null, $apellidos = null, $email = null,
                                   $telefono = null, $voucher = null, $idreserva = null) {
        $em     = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('res.id')
            ->addSelect('res.estado')
            ->addSelect('res.llegada')
            ->addSelect('res.salida')
            ->addSelect('res.tipoHabitacion')
            ->addSelect('res.tipoPension')
            ->addSelect('res.precio')
            ->addSelect('res.nombre')
            ->addSelect('res.apellidos')
            ->addSelect('res.email')
            ->addSelect('res.telefono')
            ->addSelect('res.numAdultos')
            ->addSelect('res.numNinos')
            ->addSelect('res.numBebes')
            ->addSelect('res.voucher')
            ->from('ReservasBundle:Reservas','res')
            ->where('1=1');

        if (!is_null($voucher) && $voucher != '') {
            $query->andWhere('res.voucher = :voucher');
        }
        if (!is_null($nombre) && $nombre != '') {
            $query->andWhere('res.nombre = :nombre');
        }
        if (!is_null($apellidos) && $apellidos != '') {
            $query->andWhere('res.apellidos = :apellidos');
        }
        if (!is_null($email) && $email != '') {
            $query->andWhere('res.email = :email');
        }
        if (!is_null($idreserva) && $idreserva != '') {
            $query->andWhere('res.id = :idreserva');
        }
        if (!is_null($voucher) && $voucher != '') {
            $query->setParameter('voucher', strtoupper($voucher));
        }
        if (!is_null($nombre) && $nombre != '') {
            $query->setParameter('nombre', strtoupper($nombre));
        }
        if (!is_null($apellidos) && $apellidos != '') {
            $query->setParameter('apellidos', strtoupper($apellidos));
        }
        if (!is_null($email) && $email != '') {
            $query->setParameter('email', strtolower($email));
        }
        if (!is_null($idreserva) && $idreserva != '') {
            $query->setParameter('idreserva', $idreserva);
        }
//        if ($email) {
//            $query->andWhere('res.email = :email');
//        }
//        if ($telefono) {
//            $query->andWhere('res.telefono = :telefono');
//        }

        $result = $query->getQuery()->getArrayResult();

        return $result;
    }

    public function crearCodigo() {
        $codigo     = md5(microtime());
        $em         = $this->getEntityManager();
        $reservas   = $em->getRepository('ReservasBundle:Reservas')->findBy(array('voucher' => $codigo));
        if (count($reservas) == 0) {
            return $codigo;
        } else {
            $this->crearCodigo();
        }
    }
}
